person_width = 2
person_height = 40
slot_width = 7
platform_pixel_width = 200
platform_pixel_height = 21
platform_width_factor = 6
platform_height_factor = 1
floor_height=50
update_frames = 5 #refresh screen after every n draws, when used. Higher equals faster animation.